// <auto-generated />
using Arch3DAr.Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arch3DAr.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609000000_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arch3DAr.Backend.Domain.Project", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ClientLabel").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<string>("ErrorMessage").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("GlbObjectKey").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<string>("IfcObjectKey").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<Guid>("OwnerId").HasColumnType("uuid");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<string>("ThumbnailObjectKey").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<DateTimeOffset?>("PublishedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTimeOffset?>("ConversionStartedAt").HasColumnType("timestamp with time zone");
                    b.Property<long?>("ConversionDurationMs").HasColumnType("bigint");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<long?>("IfcSizeBytes").HasColumnType("bigint");
                    b.HasKey("Id");
                    b.ToTable("projects", (string)null);
                    b.HasIndex("OwnerId").HasDatabaseName("ix_projects_owner_id");
                    b.HasIndex("Status").HasDatabaseName("ix_projects_status");
                    b.HasIndex(new[] { "OwnerId", "CreatedAt" }, "ix_projects_owner_id_created_at").IsDescending(false, true);
                });

            modelBuilder.Entity("Arch3DAr.Backend.Domain.ShareLink", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("QrCodeObjectKey").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<Guid>("ProjectId").HasColumnType("uuid");
                    b.Property<Guid>("PublicToken").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.ToTable("share_links", (string)null);
                    b.HasIndex(new[] { "ProjectId" }, "ux_share_links_project_id").IsUnique();
                    b.HasIndex(new[] { "PublicToken" }, "ux_share_links_public_token").IsUnique();
                });
#pragma warning restore 612, 618
        }
    }
}
