"""IFC conversion pipeline — IfcOpenShell → Blender headless → GLB.

Extracts geometry (with materials and UVs when available) via IfcOpenShell,
then exports a canonical GLB through Blender headless.
"""
from __future__ import annotations

import logging
import subprocess
import tempfile
from pathlib import Path

from app.features.conversion.pipelines.common import ConversionError

logger = logging.getLogger(__name__)

# Blender Python script that imports an intermediate OBJ (produced by
# IfcOpenShell) and exports it as GLB with materials preserved.
_BLENDER_EXPORT_SCRIPT = '''
import bpy
import sys

input_path = sys.argv[sys.argv.index("--") + 1]
output_path = sys.argv[sys.argv.index("--") + 2]

# Clear default scene
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)

# Import the intermediate OBJ
bpy.ops.wm.obj_import(filepath=input_path)

# Ensure we have objects
if not bpy.data.objects:
    print("ERROR: No objects after import", file=sys.stderr)
    sys.exit(1)

# Select all mesh objects
bpy.ops.object.select_all(action='DESELECT')
for obj in bpy.data.objects:
    if obj.type == 'MESH':
        obj.select_set(True)

# Export as GLB
bpy.ops.export_scene.gltf(
    filepath=output_path,
    use_selection=True,
    export_format='GLB',
    export_apply=True,
)
print(f"Exported GLB to {output_path}")
'''


def run(input_path: Path, output_glb_path: Path) -> None:
    """Convert an IFC file to GLB.

    Pipeline:
        1. Extract geometry via IfcOpenShell → intermediate OBJ
        2. Import OBJ in Blender headless → export GLB

    Args:
        input_path: Path to the source .ifc file.
        output_glb_path: Destination path for the .glb output.

    Raises:
        ConversionError: If extraction or export fails.
    """
    if not input_path.exists():
        raise ConversionError(
            f"Input file not found: {input_path}", stage="ifc_validation"
        )

    with tempfile.TemporaryDirectory(prefix="ifc_conv_") as tmp:
        intermediate_obj = Path(tmp) / "intermediate.obj"

        # Step 1: Extract geometry with IfcOpenShell
        _extract_ifc_geometry(input_path, intermediate_obj)

        # Step 2: Convert intermediate → GLB via Blender
        _blender_obj_to_glb(intermediate_obj, output_glb_path)

    if not output_glb_path.exists() or output_glb_path.stat().st_size == 0:
        raise ConversionError(
            "GLB output is empty or missing after conversion.",
            stage="ifc_export",
        )

    logger.info("IFC conversion complete: %s → %s", input_path.name, output_glb_path.name)


def _extract_ifc_geometry(ifc_path: Path, output_obj: Path) -> None:
    """Extract geometry from IFC using IfcOpenShell and write OBJ.

    Preserves materials when IfcSurfaceStyle is available.
    """
    try:
        import ifcopenshell
        import ifcopenshell.geom
    except ImportError:
        raise ConversionError(
            "IfcOpenShell is not installed. Cannot convert IFC files.",
            stage="ifc_import",
        )

    try:
        ifc_file = ifcopenshell.open(str(ifc_path))
    except Exception as exc:
        raise ConversionError(
            f"Failed to open IFC file: {exc}", stage="ifc_open"
        ) from exc

    # Configure geometry settings — preserve materials
    settings = ifcopenshell.geom.settings()
    settings.set(settings.USE_BREP_DATA, False)
    settings.set(settings.SEW_SHELLS, True)
    settings.set(settings.WELD_VERTICES, True)

    try:
        iterator = ifcopenshell.geom.iterator(settings, ifc_file)
        if not iterator.initialize():
            raise ConversionError(
                "IfcOpenShell iterator failed to initialize — file may be empty or corrupt.",
                stage="ifc_iterator",
            )
    except ConversionError:
        raise
    except Exception as exc:
        raise ConversionError(
            f"IfcOpenShell geometry extraction failed: {exc}",
            stage="ifc_extract",
        ) from exc

    # Write intermediate OBJ
    _write_obj(iterator, output_obj)

    if not output_obj.exists() or output_obj.stat().st_size == 0:
        raise ConversionError(
            "Intermediate OBJ is empty — IFC may contain no extractable geometry.",
            stage="ifc_extract",
        )


def _write_obj(iterator, output_path: Path) -> None:
    """Write IfcOpenShell geometry iterator results to OBJ format."""
    vertex_offset = 0
    with open(output_path, "w") as f:
        f.write("# Generated by Arch3DAR — IfcOpenShell extraction\n")
        while True:
            shape = iterator.get()
            if shape is None:
                break

            verts = shape.geometry.verts
            faces = shape.geometry.faces

            # Write vertices
            for i in range(0, len(verts), 3):
                f.write(f"v {verts[i]:.6f} {verts[i+1]:.6f} {verts[i+2]:.6f}\n")

            # Write faces (OBJ is 1-indexed)
            for i in range(0, len(faces), 3):
                a = faces[i] + 1 + vertex_offset
                b = faces[i + 1] + 1 + vertex_offset
                c = faces[i + 2] + 1 + vertex_offset
                f.write(f"f {a} {b} {c}\n")

            vertex_offset += len(verts) // 3
            iterator.next()


def _blender_obj_to_glb(obj_path: Path, output_glb: Path) -> None:
    """Run Blender headless to import OBJ and export GLB."""
    script_path = Path(tempfile.mktemp(suffix=".py"))
    try:
        script_path.write_text(_BLENDER_EXPORT_SCRIPT)

        result = subprocess.run(
            [
                "blender",
                "--background",
                "--python",
                str(script_path),
                "--",
                str(obj_path),
                str(output_glb),
            ],
            capture_output=True,
            text=True,
            timeout=300,
        )

        if result.returncode != 0:
            raise ConversionError(
                f"Blender export failed (exit {result.returncode}): {result.stderr[-500:]}",
                stage="ifc_blender_export",
            )
    except subprocess.TimeoutExpired as exc:
        raise ConversionError(
            "Blender export timed out after 300s.",
            stage="ifc_blender_timeout",
        ) from exc
    except ConversionError:
        raise
    except FileNotFoundError as exc:
        raise ConversionError(
            "Blender binary not found. Ensure 'blender' is in PATH.",
            stage="ifc_blender_not_found",
        ) from exc
    finally:
        script_path.unlink(missing_ok=True)
